spring.application.name=lms-backend
spring.datasource.url=jdbc:postgresql://ep-wandering-wave-aoihkell.c-2.ap-southeast-1.aws.neon.tech:5432/lms_db?sslmode=require
spring.datasource.username=lms_user
spring.datasource.password=LearningManagement$123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:fdsasdfghjkliuytrewqweryuioplkjhgfdsazxcvbn}